<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\PurchaseOrder;
use App\Models\Shipment;
use App\Models\ShipmentItem;
use App\Models\Warehouse;
use Illuminate\Database\Seeder;

class ShipmentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->call(PurchaseOrderSeeder::class);

        $freight_company1 = Company::create([
            'name' => 'Freight ABC',
            'contact_name' => 'Freight Company Abc',
            'parent_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'email' => 'abc@freight.co.uk',
            'phone' => '+44 6521 852 111',
            'type' => 'freight_company',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ]);

        $freight_company2 = Company::create([
            'name' => 'Freight XYZ',
            'contact_name' => 'Freight Company Xyz',
            'parent_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'email' => 'xyz@freight.co.uk',
            'phone' => '+44 6521 852 112',
            'type' => 'freight_company',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ]);

        $shipment = Shipment::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'customer_id' => null,
            'warehouse_id' => null,
            'purchase_order_id' => PurchaseOrder::first()->id,
            'supplier_id' => Company::where('type', 'supplier_company')->first()->id,
            'purchaser_freight_forwarder_id' => null,
            'supplier_freight_forwarder_id' => null,
            'draft_file' => null,
            'packaging_list_file' =>null,
            'invoice_file' => null,
            'china_invoice_file' => null,
            'bill_of_lading_file' => null,
            'telex_release_file' => null,
            'email_sent' => null,
            'departure_port' => "DP123",
            'shipping_line' => "Line Is Clear",
            'container_number' =>  "CN123",
            'booking_number' => "BK123",
            'bill_of_lading_number' => "BOLN123",
            'container_seal_number' => "CSN123",
            'off_load_hours' => null,
            'total_cartons' => null,
            'shipment_status' => null,
            'shipment_agent' => null,
            'vessel_etd' => date("Y-m-d H:i:s"),
            'uk_eta' => date("Y-m-d H:i:s"),
            'email_date' =>  null,
            'goods_load_date' => null,
            'load_date' => date("Y-m-d"),
            'expected_container_delivery_date' => null,
            'shipment_date' => date("Y-m-d"),
            'actual_container_ship_date' => null,
            'actual_arrival_date' => null,
        ]);

        ShipmentItem::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'shipment_id' => $shipment->id,
            'product_id' => 1,
            'quantity_ordered' => null,
            'quantity_delivered' => null,
            'quantity_balance' =>  null,
            'currency' => null,
            'total_price' => null,
            'unit_price' => null,
        ]);

        $shipment = Shipment::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'customer_id' => null,
            'warehouse_id' => null,
            'purchase_order_id' => PurchaseOrder::first()->id,
            'supplier_id' => Company::where('type', 'supplier_company')->first()->id,
            'purchaser_freight_forwarder_id' => null,
            'supplier_freight_forwarder_id' => null,
            'draft_file' => null,
            'packaging_list_file' =>null,
            'invoice_file' => null,
            'china_invoice_file' => null,
            'bill_of_lading_file' => null,
            'telex_release_file' => null,
            'email_sent' => null,
            'departure_port' => "DP456",
            'shipping_line' => "Line Is Clear",
            'container_number' =>  "CN456",
            'booking_number' => "BK456",
            'bill_of_lading_number' => "BOLN456",
            'container_seal_number' => "CSN456",
            'off_load_hours' => null,
            'total_cartons' => null,
            'shipment_status' => null,
            'shipment_agent' => null,
            'vessel_etd' => date("Y-m-d H:i:s"),
            'uk_eta' => date("Y-m-d H:i:s"),
            'email_date' =>  null,
            'goods_load_date' => null,
            'load_date' => date("Y-m-d"),
            'expected_container_delivery_date' => null,
            'shipment_date' => date("Y-m-d"),
            'actual_container_ship_date' => null,
            'actual_arrival_date' => null,
        ]);

        ShipmentItem::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'shipment_id' => $shipment->id,
            'product_id' => 2,
            'quantity_ordered' => null,
            'quantity_delivered' => null,
            'quantity_balance' =>  null,
            'currency' => null,
            'total_price' => null,
            'unit_price' => null,
        ]);

        $shipment = Shipment::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'customer_id' => null,
            'warehouse_id' => null,
            'purchase_order_id' => PurchaseOrder::first()->id,
            'supplier_id' => Company::where('type', 'supplier_company')->first()->id,
            'purchaser_freight_forwarder_id' => null,
            'supplier_freight_forwarder_id' => null,
            'draft_file' => null,
            'packaging_list_file' =>null,
            'invoice_file' => null,
            'china_invoice_file' => null,
            'bill_of_lading_file' => null,
            'telex_release_file' => null,
            'email_sent' => null,
            'departure_port' => "DP456",
            'shipping_line' => "Line Is Clear",
            'container_number' =>  "CN789",
            'booking_number' => "BK789",
            'bill_of_lading_number' => "BOLN789",
            'container_seal_number' => "CSN789",
            'off_load_hours' => null,
            'total_cartons' => null,
            'shipment_status' => null,
            'shipment_agent' => null,
            'vessel_etd' => date("Y-m-d H:i:s"),
            'uk_eta' => date("Y-m-d H:i:s"),
            'email_date' =>  null,
            'goods_load_date' => null,
            'load_date' => date("Y-m-d"),
            'expected_container_delivery_date' => null,
            'shipment_date' => date("Y-m-d"),
            'actual_container_ship_date' => null,
            'actual_arrival_date' => null,
        ]);

        ShipmentItem::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'shipment_id' => $shipment->id,
            'product_id' => 3,
            'quantity_ordered' => null,
            'quantity_delivered' => null,
            'quantity_balance' =>  null,
            'currency' => null,
            'total_price' => null,
            'unit_price' => null,
        ]);

        $shipment = Shipment::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'customer_id' => null,
            'warehouse_id' => null,
            'purchase_order_id' => PurchaseOrder::first()->id,
            'supplier_id' => Company::where('type', 'supplier_company')->first()->id,
            'purchaser_freight_forwarder_id' => null,
            'supplier_freight_forwarder_id' => null,
            'draft_file' => null,
            'packaging_list_file' =>null,
            'invoice_file' => null,
            'china_invoice_file' => null,
            'bill_of_lading_file' => null,
            'telex_release_file' => null,
            'email_sent' => null,
            'departure_port' => "DP951",
            'shipping_line' => "Line Is Clear",
            'container_number' =>  "CN951",
            'booking_number' => "BK951",
            'bill_of_lading_number' => "BOLN951",
            'container_seal_number' => "CSN951",
            'off_load_hours' => null,
            'total_cartons' => null,
            'shipment_status' => null,
            'shipment_agent' => null,
            'vessel_etd' => date("Y-m-d H:i:s"),
            'uk_eta' => date("Y-m-d H:i:s"),
            'email_date' =>  null,
            'goods_load_date' => null,
            'load_date' => date("Y-m-d"),
            'expected_container_delivery_date' => null,
            'shipment_date' => date("Y-m-d"),
            'actual_container_ship_date' => null,
            'actual_arrival_date' => null,
        ]);

        ShipmentItem::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'shipment_id' => $shipment->id,
            'product_id' => 4,
            'quantity_ordered' => null,
            'quantity_delivered' => null,
            'quantity_balance' =>  null,
            'currency' => null,
            'total_price' => null,
            'unit_price' => null,
        ]);

        $shipment = Shipment::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'customer_id' => null,
            'warehouse_id' => null,
            'purchase_order_id' => PurchaseOrder::first()->id,
            'supplier_id' => Company::where('type', 'supplier_company')->first()->id,
            'purchaser_freight_forwarder_id' => null,
            'supplier_freight_forwarder_id' => null,
            'draft_file' => null,
            'packaging_list_file' =>null,
            'invoice_file' => null,
            'china_invoice_file' => null,
            'bill_of_lading_file' => null,
            'telex_release_file' => null,
            'email_sent' => null,
            'departure_port' => "DP753",
            'shipping_line' => "Line Is Clear",
            'container_number' =>  "CN753",
            'booking_number' => "BK753",
            'bill_of_lading_number' => "BOLN753",
            'container_seal_number' => "CSN753",
            'off_load_hours' => null,
            'total_cartons' => null,
            'shipment_status' => null,
            'shipment_agent' => null,
            'vessel_etd' => date("Y-m-d H:i:s"),
            'uk_eta' => date("Y-m-d H:i:s"),
            'email_date' =>  null,
            'goods_load_date' => null,
            'load_date' => date("Y-m-d"),
            'expected_container_delivery_date' => null,
            'shipment_date' => date("Y-m-d"),
            'actual_container_ship_date' => null,
            'actual_arrival_date' => null,
        ]);

        ShipmentItem::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'shipment_id' => $shipment->id,
            'product_id' => 5,
            'quantity_ordered' => null,
            'quantity_delivered' => null,
            'quantity_balance' =>  null,
            'currency' => null,
            'total_price' => null,
            'unit_price' => null,
        ]);

        $shipment = Shipment::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'customer_id' => null,
            'warehouse_id' => null,
            'purchase_order_id' => PurchaseOrder::first()->id,
            'supplier_id' => Company::where('type', 'supplier_company')->first()->id,
            'purchaser_freight_forwarder_id' => $freight_company1->id,
            'supplier_freight_forwarder_id' => $freight_company2->id,
            'draft_file' => "DF321",
            'packaging_list_file' =>"PLF321",
            'invoice_file' => "IF321",
            'china_invoice_file' => "CIF321",
            'bill_of_lading_file' => "BOLF321",
            'telex_release_file' => "TRF321",
            'email_sent' => '321@example.com.uk',
            'departure_port' => "DP321",
            'shipping_line' => "Line Is Clear",
            'container_number' =>  "CN321",
            'booking_number' => "BK321",
            'bill_of_lading_number' => "BOLN321",
            'container_seal_number' => "CSN321",
            'off_load_hours' => "321",
            'total_cartons' => 1,
            'shipment_status' => "unpaid",
            'shipment_agent' => "england_agent",
            'vessel_etd' => date("Y-m-d H:i:s"),
            'uk_eta' => date("Y-m-d H:i:s"),
            'email_date' =>  date("Y-m-d H:i:s"),
            'goods_load_date' => date("Y-m-d H:i:s"),
            'load_date' => date("Y-m-d"),
            'expected_container_delivery_date' => null,
            'shipment_date' => date("Y-m-d"),
            'actual_container_ship_date' => date("Y-m-d H:i:s"),
            'actual_arrival_date' => date("Y-m-d H:i:s"),
        ]);

        ShipmentItem::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'shipment_id' => $shipment->id,
            'product_id' => 6,
            'quantity_ordered' => 5,
            'quantity_delivered' => 3,
            'quantity_balance' =>  2,
            'currency' => 61,
            'total_price' => 20,
            'unit_price' => 2,
        ]);

        $shipment = Shipment::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'customer_id' => null,
            'warehouse_id' => null,
            'purchase_order_id' => PurchaseOrder::first()->id,
            'supplier_id' => Company::where('type', 'supplier_company')->first()->id,
            'purchaser_freight_forwarder_id' => $freight_company1->id,
            'supplier_freight_forwarder_id' => $freight_company2->id,
            'draft_file' => "DF654",
            'packaging_list_file' =>"PLF654",
            'invoice_file' => "IF654",
            'china_invoice_file' => "CIF654",
            'bill_of_lading_file' => "BOLF654",
            'telex_release_file' => "TRF654",
            'email_sent' => '654@example.com.uk',
            'departure_port' => "DP654",
            'shipping_line' => "Line Is Clear",
            'container_number' =>  "CN654",
            'booking_number' => "BK654",
            'bill_of_lading_number' => "BOLN654",
            'container_seal_number' => "CSN654",
            'off_load_hours' => "654",
            'total_cartons' => 1,
            'shipment_status' => "unpaid",
            'shipment_agent' => "england_agent",
            'vessel_etd' => date("Y-m-d H:i:s"),
            'uk_eta' => date("Y-m-d H:i:s"),
            'email_date' =>  date("Y-m-d H:i:s"),
            'goods_load_date' => date("Y-m-d H:i:s"),
            'load_date' => date("Y-m-d"),
            'expected_container_delivery_date' => null,
            'shipment_date' => date("Y-m-d"),
            'actual_container_ship_date' => date("Y-m-d H:i:s"),
            'actual_arrival_date' => date("Y-m-d H:i:s"),
        ]);

        ShipmentItem::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'shipment_id' => $shipment->id,
            'product_id' => 7,
            'quantity_ordered' => 5,
            'quantity_delivered' => 3,
            'quantity_balance' =>  2,
            'currency' => 61,
            'total_price' => 20,
            'unit_price' => 2,
        ]);

        $shipment = Shipment::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'customer_id' => null,
            'warehouse_id' => null,
            'purchase_order_id' => PurchaseOrder::first()->id,
            'supplier_id' => Company::where('type', 'supplier_company')->first()->id,
            'purchaser_freight_forwarder_id' => $freight_company1->id,
            'supplier_freight_forwarder_id' => $freight_company2->id,
            'draft_file' => "DF987",
            'packaging_list_file' =>"PLF987",
            'invoice_file' => "IF987",
            'china_invoice_file' => "CIF987",
            'bill_of_lading_file' => "BOLF987",
            'telex_release_file' => "TRF987",
            'email_sent' => '987@example.com.uk',
            'departure_port' => "DP987",
            'shipping_line' => "Line Is Clear",
            'container_number' =>  "CN987",
            'booking_number' => "BK987",
            'bill_of_lading_number' => "BOLN987",
            'container_seal_number' => "CSN987",
            'off_load_hours' => "987",
            'total_cartons' => 1,
            'shipment_status' => "unpaid",
            'shipment_agent' => "england_agent",
            'vessel_etd' => date("Y-m-d H:i:s"),
            'uk_eta' => date("Y-m-d H:i:s"),
            'email_date' =>  date("Y-m-d H:i:s"),
            'goods_load_date' => date("Y-m-d H:i:s"),
            'load_date' => date("Y-m-d"),
            'expected_container_delivery_date' => null,
            'shipment_date' => date("Y-m-d"),
            'actual_container_ship_date' => date("Y-m-d H:i:s"),
            'actual_arrival_date' => date("Y-m-d H:i:s"),
        ]);

        ShipmentItem::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'shipment_id' => $shipment->id,
            'product_id' => 8,
            'quantity_ordered' => 5,
            'quantity_delivered' => 3,
            'quantity_balance' =>  2,
            'currency' => 61,
            'total_price' => 20,
            'unit_price' => 2,
        ]);

        $shipment = Shipment::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'customer_id' => null,
            'warehouse_id' => null,
            'purchase_order_id' => PurchaseOrder::first()->id,
            'supplier_id' => Company::where('type', 'supplier_company')->first()->id,
            'purchaser_freight_forwarder_id' => $freight_company1->id,
            'supplier_freight_forwarder_id' => $freight_company2->id,
            'draft_file' => "DF159",
            'packaging_list_file' =>"PLF159",
            'invoice_file' => "IF159",
            'china_invoice_file' => "CIF159",
            'bill_of_lading_file' => "BOLF159",
            'telex_release_file' => "TRF159",
            'email_sent' => '159@example.com.uk',
            'departure_port' => "DP159",
            'shipping_line' => "Line Is Clear",
            'container_number' =>  "CN159",
            'booking_number' => "BK159",
            'bill_of_lading_number' => "BOLN159",
            'container_seal_number' => "CSN159",
            'off_load_hours' => "159",
            'total_cartons' => 1,
            'shipment_status' => "partial_paid",
            'shipment_agent' => "england_agent",
            'vessel_etd' => date("Y-m-d H:i:s"),
            'uk_eta' => date("Y-m-d H:i:s"),
            'email_date' =>  date("Y-m-d H:i:s"),
            'goods_load_date' => date("Y-m-d H:i:s"),
            'load_date' => date("Y-m-d"),
            'expected_container_delivery_date' => null,
            'shipment_date' => date("Y-m-d"),
            'actual_container_ship_date' => date("Y-m-d H:i:s"),
            'actual_arrival_date' => date("Y-m-d H:i:s"),
        ]);

        ShipmentItem::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'shipment_id' => $shipment->id,
            'product_id' => 9,
            'quantity_ordered' => 5,
            'quantity_delivered' => 3,
            'quantity_balance' =>  2,
            'currency' => 61,
            'total_price' => 20,
            'unit_price' => 2,
        ]);

        $shipment = Shipment::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'customer_id' => null,
            'warehouse_id' => null,
            'purchase_order_id' => PurchaseOrder::first()->id,
            'supplier_id' => Company::where('type', 'supplier_company')->first()->id,
            'purchaser_freight_forwarder_id' => $freight_company1->id,
            'supplier_freight_forwarder_id' => $freight_company2->id,
            'draft_file' => "DF357",
            'packaging_list_file' =>"PLF357",
            'invoice_file' => "IF357",
            'china_invoice_file' => "CIF357",
            'bill_of_lading_file' => "BOLF357",
            'telex_release_file' => "TRF357",
            'email_sent' => '357@example.com.uk',
            'departure_port' => "DP357",
            'shipping_line' => "Line Is Clear",
            'container_number' =>  "CN357",
            'booking_number' => "BK357",
            'bill_of_lading_number' => "BOLN357",
            'container_seal_number' => "CSN357",
            'off_load_hours' => "357",
            'total_cartons' => 1,
            'shipment_status' => "paid",
            'shipment_agent' => "england_agent",
            'vessel_etd' => date("Y-m-d H:i:s"),
            'uk_eta' => date("Y-m-d H:i:s"),
            'email_date' =>  date("Y-m-d H:i:s"),
            'goods_load_date' => date("Y-m-d H:i:s"),
            'load_date' => date("Y-m-d"),
            'expected_container_delivery_date' => null,
            'shipment_date' => date("Y-m-d"),
            'actual_container_ship_date' => date("Y-m-d H:i:s"),
            'actual_arrival_date' => date("Y-m-d H:i:s"),
        ]);

        ShipmentItem::create([
            'company_id' => Company::where('name', 'Alfa Mohuha')->where('contact_name','Mohsin Shah')->where('email','mohsin.shah@alfamohuha.com')->first()->id,
            'shipment_id' => $shipment->id,
            'product_id' => 10,
            'quantity_ordered' => 5,
            'quantity_delivered' => 3,
            'quantity_balance' =>  2,
            'currency' => 61,
            'total_price' => 20,
            'unit_price' => 2,
        ]);

    }
}
